kind: Namespace
apiVersion: v1
metadata:
  name: xfusion
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: xfusion
spec:
  replicas: 4
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 1
        maxUnavailable: 2 
  selector:
    matchLabels:
      app: httpd 
  template:
    metadata:
      labels:
        app: httpd 
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.28
