apiVersion: v1
kind: Namespace
metadata: 
  name: vote

---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
  labels:
    name: vote-service
    app: voting-app
spec:
  type: NodePort
  selector:
     name: vote-pod
     app: voting-app
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
  labels:
    app: voting-app
    name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: vote-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: vote-pod
    spec:
      containers:
      - name: vote
        image: kodekloud/examplevotingapp_vote:before
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote
spec:
  type: ClusterIP
  selector:
    app: voting-app
    name: redis-pod
  ports:
    - name: client
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
  labels:
    app: voting-app
    name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: redis-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: redis-pod
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}       

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
  labels:
    app: voting-app
    name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: worker-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: worker-pod
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
  labels:
    name: postgres-service
    app: voting-app
spec:
  type: ClusterIP
  selector:
    app: voting-app
    name: db-pod
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote
  labels:
    app: voting-app
    name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: db-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: db-pod
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name:  POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
  labels:
    app: voting-app
    name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: result-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: result-pod
    spec:
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:before
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
  labels:
    name: result-service
    app: voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
    name: result-pod
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001
