apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xfusion
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-xfusion
            image: httpd:latest
            args:
            - /bin/sh
            - -c
            - echo Welcome to xfusioncorp.
          restartPolicy: OnFailure
~                                   
